"""Create core parking database schema

Revision ID: b5a86e3bf717
Revises: cf51dad590ad
Create Date: 2026-08-15 22:13:45.150941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a86e3bf717'
down_revision: Union[str, Sequence[str], None] = 'cf51dad590ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', name='adminrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_user_id'), 'admins', ['user_id'], unique=True)
    op.create_table('parking_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('total_slots >= 0', name='check_total_slots_zone'),
    sa.ForeignKeyConstraint(['facility_id'], ['parking_facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'name', name='uq_facility_zone_name')
    )
    op.create_index(op.f('ix_parking_zones_facility_id'), 'parking_zones', ['facility_id'], unique=False)
    op.create_index(op.f('ix_parking_zones_id'), 'parking_zones', ['id'], unique=False)
    op.add_column('parking_facilities', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('parking_facilities', sa.Column('state', sa.String(length=128), nullable=True))
    op.add_column('parking_facilities', sa.Column('postal_code', sa.String(length=32), nullable=True))
    op.add_column('parking_facilities', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('parking_facilities', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('parking_facilities', sa.Column('total_slots', sa.Integer(), nullable=False))
    op.add_column('parking_facilities', sa.Column('operating_start_time', sa.String(length=16), nullable=True))
    op.add_column('parking_facilities', sa.Column('operating_end_time', sa.String(length=16), nullable=True))
    op.add_column('parking_facilities', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('parking_facilities', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('parking_facilities', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_parking_facilities_city'), 'parking_facilities', ['city'], unique=False)
    op.create_index(op.f('ix_parking_facilities_latitude'), 'parking_facilities', ['latitude'], unique=False)
    op.create_index(op.f('ix_parking_facilities_longitude'), 'parking_facilities', ['longitude'], unique=False)
    op.add_column('parking_sessions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('parking_sessions', sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('parking_sessions', sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parking_sessions', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('parking_sessions', sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='parkingsessionstatus'), nullable=False))
    op.add_column('parking_sessions', sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('parking_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('parking_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_index(op.f('ix_parking_sessions_check_in_time'), 'parking_sessions', ['check_in_time'], unique=False)
    op.create_index(op.f('ix_parking_sessions_check_out_time'), 'parking_sessions', ['check_out_time'], unique=False)
    op.create_index(op.f('ix_parking_sessions_reservation_id'), 'parking_sessions', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_parking_sessions_slot_id'), 'parking_sessions', ['slot_id'], unique=False)
    op.create_index(op.f('ix_parking_sessions_status'), 'parking_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_parking_sessions_user_id'), 'parking_sessions', ['user_id'], unique=False)
    op.drop_constraint(None, 'parking_sessions', type_='foreignkey')
    op.drop_constraint(None, 'parking_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'parking_sessions', 'reservations', ['reservation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'parking_sessions', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'parking_sessions', 'parking_slots', ['slot_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('parking_sessions', 'ended_at')
    op.drop_column('parking_sessions', 'fee')
    op.drop_column('parking_sessions', 'started_at')
    op.add_column('parking_slots', sa.Column('zone_id', sa.Integer(), nullable=False))
    op.add_column('parking_slots', sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', name='parkingslotstatus'), nullable=False))
    op.add_column('parking_slots', sa.Column('vehicle_type', sa.Enum('CAR', 'BIKE', 'EV', 'OTHER', name='vehicletype'), nullable=False))
    op.add_column('parking_slots', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('parking_slots', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('parking_slots', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_index(op.f('ix_parking_slots_status'), 'parking_slots', ['status'], unique=False)
    op.create_index(op.f('ix_parking_slots_zone_id'), 'parking_slots', ['zone_id'], unique=False)
    op.create_unique_constraint('uq_zone_slot_number', 'parking_slots', ['zone_id', 'slot_number'])
    op.drop_constraint(None, 'parking_slots', type_='foreignkey')
    op.create_foreign_key(None, 'parking_slots', 'parking_zones', ['zone_id'], ['id'], ondelete='CASCADE')
    op.drop_column('parking_slots', 'is_available')
    op.drop_column('parking_slots', 'facility_id')
    op.add_column('payments', sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'UPI', 'ONLINE', name='paymentmethod'), nullable=False))
    op.add_column('payments', sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False))
    op.add_column('payments', sa.Column('transaction_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('payments', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_payments_payment_status'), 'payments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payments_session_id'), 'payments', ['session_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'parking_sessions', ['session_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('payments', 'provider_reference')
    op.drop_column('payments', 'provider')
    op.add_column('reservations', sa.Column('reservation_start', sa.DateTime(timezone=True), nullable=False))
    op.add_column('reservations', sa.Column('reservation_end', sa.DateTime(timezone=True), nullable=False))
    op.add_column('reservations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_index(op.f('ix_reservations_reservation_end'), 'reservations', ['reservation_end'], unique=False)
    op.create_index(op.f('ix_reservations_reservation_start'), 'reservations', ['reservation_start'], unique=False)
    op.create_index(op.f('ix_reservations_slot_id'), 'reservations', ['slot_id'], unique=False)
    op.create_index(op.f('ix_reservations_status'), 'reservations', ['status'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'parking_slots', ['slot_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reservations', 'start_time')
    op.drop_column('reservations', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('end_time', sa.DATETIME(), nullable=False))
    op.add_column('reservations', sa.Column('start_time', sa.DATETIME(), nullable=False))
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'parking_slots', ['slot_id'], ['id'])
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_status'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_slot_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_reservation_start'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_reservation_end'), table_name='reservations')
    op.drop_column('reservations', 'updated_at')
    op.drop_column('reservations', 'reservation_end')
    op.drop_column('reservations', 'reservation_start')
    op.add_column('payments', sa.Column('provider', sa.VARCHAR(length=128), nullable=True))
    op.add_column('payments', sa.Column('provider_reference', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'parking_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_status'), table_name='payments')
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('payments', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'transaction_id')
    op.drop_column('payments', 'payment_status')
    op.drop_column('payments', 'payment_method')
    op.add_column('parking_slots', sa.Column('facility_id', sa.INTEGER(), nullable=False))
    op.add_column('parking_slots', sa.Column('is_available', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'parking_slots', type_='foreignkey')
    op.create_foreign_key(None, 'parking_slots', 'parking_facilities', ['facility_id'], ['id'])
    op.drop_constraint('uq_zone_slot_number', 'parking_slots', type_='unique')
    op.drop_index(op.f('ix_parking_slots_zone_id'), table_name='parking_slots')
    op.drop_index(op.f('ix_parking_slots_status'), table_name='parking_slots')
    op.drop_column('parking_slots', 'updated_at')
    op.drop_column('parking_slots', 'created_at')
    op.drop_column('parking_slots', 'is_active')
    op.drop_column('parking_slots', 'vehicle_type')
    op.drop_column('parking_slots', 'status')
    op.drop_column('parking_slots', 'zone_id')
    op.add_column('parking_sessions', sa.Column('started_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('parking_sessions', sa.Column('fee', sa.FLOAT(), nullable=True))
    op.add_column('parking_sessions', sa.Column('ended_at', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'parking_sessions', type_='foreignkey')
    op.drop_constraint(None, 'parking_sessions', type_='foreignkey')
    op.drop_constraint(None, 'parking_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'parking_sessions', 'reservations', ['reservation_id'], ['id'])
    op.create_foreign_key(None, 'parking_sessions', 'parking_slots', ['slot_id'], ['id'])
    op.drop_index(op.f('ix_parking_sessions_user_id'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_status'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_slot_id'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_reservation_id'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_check_out_time'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_check_in_time'), table_name='parking_sessions')
    op.drop_column('parking_sessions', 'updated_at')
    op.drop_column('parking_sessions', 'created_at')
    op.drop_column('parking_sessions', 'fee_amount')
    op.drop_column('parking_sessions', 'status')
    op.drop_column('parking_sessions', 'duration_minutes')
    op.drop_column('parking_sessions', 'check_out_time')
    op.drop_column('parking_sessions', 'check_in_time')
    op.drop_column('parking_sessions', 'user_id')
    op.drop_index(op.f('ix_parking_facilities_longitude'), table_name='parking_facilities')
    op.drop_index(op.f('ix_parking_facilities_latitude'), table_name='parking_facilities')
    op.drop_index(op.f('ix_parking_facilities_city'), table_name='parking_facilities')
    op.alter_column('parking_facilities', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('parking_facilities', 'updated_at')
    op.drop_column('parking_facilities', 'created_at')
    op.drop_column('parking_facilities', 'operating_end_time')
    op.drop_column('parking_facilities', 'operating_start_time')
    op.drop_column('parking_facilities', 'total_slots')
    op.drop_column('parking_facilities', 'longitude')
    op.drop_column('parking_facilities', 'latitude')
    op.drop_column('parking_facilities', 'postal_code')
    op.drop_column('parking_facilities', 'state')
    op.drop_column('parking_facilities', 'description')
    op.drop_index(op.f('ix_parking_zones_id'), table_name='parking_zones')
    op.drop_index(op.f('ix_parking_zones_facility_id'), table_name='parking_zones')
    op.drop_table('parking_zones')
    op.drop_index(op.f('ix_admins_user_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
